name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check_commit:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # A PR should not contain too many commits
          fetch-depth: 10
      - name: Validate commit messages
        run: |
          git show-ref
          curl -sSfL https://github.com/convco/convco/releases/latest/download/convco-ubuntu.zip | zcat > convco
          chmod +x convco
          ./convco check ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}
          rm convco

  linux:
    name: linux
    needs: check_commit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta 
          - stable minus 8 releases
        feature:
          - d
          - d,images
          - z
          - z,images
          - z,d
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy, rustfmt
      - run: sudo apt-get install -y libdbus-1-dev

      - name: check (default features)
        run: cargo check

      - name: cargo-fmt
        run: cargo fmt --all --check

      - name: check (${{matrix.feature}})
        run: cargo check --no-default-features --features ${{matrix.feature}}

      - name: test (default features)
        run: cargo test

      - name: test lib (${{matrix.feature}})
        run: cargo test --lib --no-default-features --features ${{matrix.feature}}

      - name: test tests (${{matrix.feature}})
        run: cargo test --tests --no-default-features --features ${{matrix.feature}}

      - name: test docs (${{matrix.feature}})
        run: cargo test --doc --no-default-features --features ${{matrix.feature}}

      - name: clippy (default features)
        run: cargo clippy

      - name: clippy (${{matrix.feature}})
        run: cargo clippy --no-default-features --features ${{matrix.feature}} -- -D warnings

  windows:
    name: windows
    runs-on: windows-latest
    strategy:
      matrix:
        rust:
          - stable
          - 1.70.0
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - run: rustup component add clippy
      - name: check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-run
      - name: clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  macos:
    name: macos
    runs-on: macos-latest
    strategy:
      matrix:
        rust:
          - stable
          - 1.70.0
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - run: rustup component add clippy
      - name: check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-run
      - name: clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
