name: Pull request
# This workflow is triggered on pushes to the repository.
on: [ pull_request, workflow_call, workflow_dispatch ]

jobs:
  check:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # A PR should not contain too many commits
          fetch-depth: 10
      - name: Validate commit messages
        run: |
          git show-ref
          curl -sSfL https://github.com/convco/convco/releases/latest/download/convco-ubuntu.zip | zcat > convco
          chmod +x convco
          ./convco check ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}
          rm convco

  check_fmt_clippy:
    name: Check Format
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: cargo-fmt
        run: cargo fmt --all --check

      #- name: clippy
      #  run: cargo clippy --all-features -- -D warnings

